name: "Auto Merge Bot"
description: "Bot which enables or disable auto-merge"
author: Bullrich
branding:
  icon: git-merge
  color: red
inputs:
  GITHUB_TOKEN:
    required: true
    description: The token to access the repo information
  MERGE_METHOD:
    required: false
    description: The merge method to use. Must be one of MERGE, SQUASH or REBASE.
    default: SQUASH
  SILENT:
    required: false
    description: If true, the bot will not post a comment on the PR.
outputs:
  repo:
    description: 'The name of the repo in owner/repo pattern'

runs:
  using: 'docker'
  image: 'Dockerfile'
